HYD-4368 Support DNE Phase I in the IML GUI and Backend.
This means:

1) Be able to select N MDTs in the create filesystem screen.
2) Be able to add more MDTs to an existing FS.
3) Be able to remove non 0 MDTs.

The changes are minimal as IML was pretty much already written to
handle multiple MDT's. The code required mostly removal of exceptions
and a little bit of generalisation.

The unit tests have been expanded to do some multiple MDT testing.
Selenium testing as well was expanded to test the multiple MDT case.
This change requires the simultaneous landing of two tickets HYD-4368
and HYD-4320.

HYD-4368 is the backend changes HYD-4320 is the frontend changes

Change-Id: I719e679bb9b173d136a67d5038d05c645181cb8e
Signed-off-by: Chris Gearing <chris.gearing@intel.com>
Reviewed-on: http://review.whamcloud.com/14327
Tested-by: Chroma Test User <hpdd-devops@intel.com>
Reviewed-by: Mathieu Drapeau <mathieu.drapeau@intel.com>
Reviewed-by: Joe Grund <joe.grund@intel.com>
Reviewed-on: http://review.whamcloud.com/14654
Tested-by: Jenkins
Reviewed-on: http://review.whamcloud.com/14445

diff --git a/chroma-manager/tests/framework/integration/existing_filesystem_configuration/jenkins_steps/main b/chroma-manager/tests/framework/integration/existing_filesystem_configuration/jenkins_steps/main
--- a/chroma-manager/tests/framework/integration/existing_filesystem_configuration/jenkins_steps/main
+++ b/chroma-manager/tests/framework/integration/existing_filesystem_configuration/jenkins_steps/main
@@ -76,37 +76,44 @@ echo "Beginning automated efs run..."
 ORIGINAL_CLUSTER_CONFIG=$(ls $PWD/existing_filesystem_configuration_cluster_cfg.json)
 chroma/chroma-manager/tests/framework/integration/existing_filesystem_configuration/cluster_setup
 
-for test_ha in true false; do
-    if [ $test_ha == true ]; then
-        device_types_to_test=(linux)
-    else
-        #devices_to_test=(zfs lvm mdraid linux); do  <--- mdraid Coming soon.
-        device_types_to_test=(zfs lvm linux)
-    fi
-
-    for device_type in ${device_types_to_test[@]}; do
-        # Not all HA tests are enabled, yet
-        if [[ ( $test_ha == true ) && ( $device_type == zfs || $device_type == lvm ) ]]; then
-            continue
+for dne in true false; do
+    for test_ha in true false; do
+        if [ $test_ha == true ]; then
+            device_types_to_test=(linux)
+        else
+            #devices_to_test=(zfs lvm mdraid linux); do  <--- mdraid Coming soon.
+            device_types_to_test=(zfs lvm linux)
         fi
 
-        echo "Beginning automated ${device_type} run..."
+        for device_type in ${device_types_to_test[@]}; do
+            echo "Beginning automated ${device_type} run..."
 
-        export CLUSTER_CONFIG=$PWD/existing_filesystem_configuration_cluster_cfg_${device_type}_HA_is_${test_ha}.json
+            export CLUSTER_CONFIG=$PWD/existing_filesystem_configuration_cluster_cfg_${device_type}_HA_is_${test_ha}_dne_is_${dne}.json
 
-        sed -e s/\"device_type\"\:\ \"linux\"/\"device_type\":\ \"${device_type}\"/g $ORIGINAL_CLUSTER_CONFIG > $CLUSTER_CONFIG
-        sed -i -e s/\"test_ha\"\:\ true/\"test_ha\":\ ${test_ha}/g $CLUSTER_CONFIG
+            sed -e s/\"device_type\"\:\ \"linux\"/\"device_type\":\ \"${device_type}\"/g $ORIGINAL_CLUSTER_CONFIG > $CLUSTER_CONFIG
+            sed -i -e s/\"test_ha\"\:\ true/\"test_ha\":\ ${test_ha}/g $CLUSTER_CONFIG
 
-        export XML_RESULTS_FILE="~/test_report_${device_type}_HA_is_${test_ha}.xml"
+            # One Kind entry is defined as "kind": "OSTorMDT" set it to be an OST for !dne or an MDT for dne
+            # The replace actually does a number of things such as the mount point etc.
+            if [ $dne == true]; then
+                sed -i -e s/OSTorMDT/MDT/g $CLUSTER_CONFIG
+                sed -i -e s/ostORmdt/mdt/g $CLUSTER_CONFIG
+            else
+                sed -i -e s/OSTorMDT/OST/g $CLUSTER_CONFIG
+                sed -i -e s/ostORmdt/ost/g $CLUSTER_CONFIG
+            fi
 
-        # Don't stop on error for this case because if one iteration of this loop fails we still want to perform the other iterations
-        set +e
-        chroma/chroma-manager/tests/framework/integration/existing_filesystem_configuration/filesystem_setup
-        cat $CLUSTER_CONFIG
-        chroma/chroma-manager/tests/framework/integration/existing_filesystem_configuration/run_tests
-        set -e
+            export XML_RESULTS_FILE="~/test_report_${device_type}_HA_is_${test_ha}.xml"
 
-        echo "Automated ${device_type} run complete."
+            # Don't stop on error for this case because if one iteration of this loop fails we still want to perform the other iterations
+            set +e
+            chroma/chroma-manager/tests/framework/integration/existing_filesystem_configuration/filesystem_setup
+            cat $CLUSTER_CONFIG
+            chroma/chroma-manager/tests/framework/integration/existing_filesystem_configuration/run_tests
+            set -e
+
+            echo "Automated ${device_type} run complete."
+        done
     done
 done
 
