HYD-4437 Use provisioner-ng for EFS tests
The provisioner-ng hardware pool is larger and easier to manage, 
allowing us to grow it more easily so we want to allow EFS take
advantage of that.

This patch also fixes a potential false positive failure in the many
iterations of this test across the DNE/HA/backing-store type loops.

Plus a fix an in the unmount code path where address was being used
rather than nodename. This bug was highlighted by the switch to
provisioner-ng.

Signed-off-by: Brian J. Murrell <brian.murrell@intel.com>
Change-Id: I4349567032bae53e6528ef8c0fffbe1c579b5453
Reviewed-on: http://review.whamcloud.com/14822
Tested-by: Chroma Test User <hpdd-devops@intel.com>
Reviewed-by: Mathieu Drapeau <mathieu.drapeau@intel.com>
Reviewed-by: Chris Gearing <chris.gearing@intel.com>

diff --git a/chroma-manager/tests/framework/integration/existing_filesystem_configuration/jenkins_steps/main b/chroma-manager/tests/framework/integration/existing_filesystem_configuration/jenkins_steps/main
--- a/chroma-manager/tests/framework/integration/existing_filesystem_configuration/jenkins_steps/main
+++ b/chroma-manager/tests/framework/integration/existing_filesystem_configuration/jenkins_steps/main
@@ -1,7 +1,5 @@
 #!/bin/bash -ex
 
-PROVISIONER=${PROVISIONER:-"ssh chromatest@autotest ./provisionchroma -v -S"}
-
 . chroma-manager/tests/framework/integration/utils/defaults.sh
 
 cd $WORKSPACE
@@ -17,28 +15,34 @@ sed -i -e "s/BUILD_JOB_NAME/${BUILD_JOB_NAME}/g" \
 
 python chroma/chroma-manager/tests/framework/utils/provisioner_interface/test_json2provisioner_json.py chroma/chroma-manager/tests/framework/integration/existing_filesystem_configuration/existing_filesystem_configuration_cluster_cfg.json provisioner_input.json
 
+# don't really need a client configured so let's save the time doing it
+sed -i -e '/lustre_client_version/c\
+            "lustre_client_version": ""' provisioner_input.json
+
 cat provisioner_input.json
 echo
 
 # Release the provisioned cluster (at exit of this script)
 trap "set +e
+set -x
 # Gather logs from nodes
 python chroma/chroma-manager/tests/integration/utils/chroma_log_collector.py $WORKSPACE/test_logs existing_filesystem_configuration_cluster_cfg.json
 
 sed -e 's/provision\": *true/provision\": false/g' < provisioner_output.json | $PROVISIONER" EXIT
 
 # Provision cluster to run tests on
-PROVISION_START_TIME=$(date '+%s')
-cat provisioner_input.json | $PROVISIONER > provisioner_output.json
-PROVISION_END_TIME=$(date '+%s')
-PROVISION_DURATION=$(( $PROVISION_END_TIME-$PROVISION_START_TIME ))
+PROVISION_START_TIME=$SECONDS
+rc=0
+cat provisioner_input.json | $PROVISIONER > provisioner_output.json || rc=$?
+PROVISION_END_TIME=$SECONDS
+PROVISION_DURATION=$((PROVISION_END_TIME-PROVISION_START_TIME))
 echo "$PROVISION_DURATION" > $WORKSPACE/provision_duration.txt
-echo "Provision took $(( $PROVISION_DURATION/60 )) minutes."
+echo "Provision took $((PROVISION_DURATION/60)) minutes."
 
 cat provisioner_output.json
 echo
 
-if ! grep '"success":true' provisioner_output.json; then
+if [ $rc != 0 ] || [ ! -s provisioner_output.json ] || grep '"success": false' provisioner_output.json; then
     echo "Cluster provisioner failed"
     cat provisioner_output.json
     exit 1
@@ -76,6 +80,7 @@ echo "Beginning automated efs run..."
 ORIGINAL_CLUSTER_CONFIG=$(ls $PWD/existing_filesystem_configuration_cluster_cfg.json)
 chroma/chroma-manager/tests/framework/integration/existing_filesystem_configuration/cluster_setup
 
+setup_rc=0
 for dne in true false; do
     for test_ha in true false; do
         if $test_ha; then
@@ -90,8 +95,8 @@ for dne in true false; do
 
             export CLUSTER_CONFIG=$PWD/existing_filesystem_configuration_cluster_cfg_${device_type}_HA_is_${test_ha}_dne_is_${dne}.json
 
-            sed -e s/\"device_type\"\:\ \"linux\"/\"device_type\":\ \"${device_type}\"/g $ORIGINAL_CLUSTER_CONFIG > $CLUSTER_CONFIG
-            sed -i -e s/\"test_ha\"\:\ true/\"test_ha\":\ ${test_ha}/g $CLUSTER_CONFIG
+            sed -e "s/\(\"device_type\": *\)\"linux\"/\1\"${device_type}\"/g" $ORIGINAL_CLUSTER_CONFIG > $CLUSTER_CONFIG
+            sed -i -e "s/\(\"test_ha\"\: *\)true/\1${test_ha}/g" $CLUSTER_CONFIG
 
             # One Kind entry is defined as "kind": "OSTorMDT" set it to be an OST for !dne or an MDT for dne
             # The replace actually does a number of things such as the mount point etc.
@@ -106,16 +111,26 @@ for dne in true false; do
             export XML_RESULTS_FILE="~/test_report_${device_type}_HA_is_${test_ha}.xml"
 
             # Don't stop on error for this case because if one iteration of this loop fails we still want to perform the other iterations
-            set +e
-            chroma/chroma-manager/tests/framework/integration/existing_filesystem_configuration/filesystem_setup
             cat $CLUSTER_CONFIG
-            chroma/chroma-manager/tests/framework/integration/existing_filesystem_configuration/run_tests
-            set -e
-
+            if ! chroma/chroma-manager/tests/framework/integration/existing_filesystem_configuration/filesystem_setup; then
+                let setup_rc+=${PIPESTATUS[0]}
+                echo "Automated ${device_type} setup failed"
+                continue
+            fi
+            if ! chroma/chroma-manager/tests/framework/integration/existing_filesystem_configuration/run_tests; then
+                let test_run_rc+=${PIPESTATUS[0]}
+                echo "Automated ${device_type} run failed"
+                continue
+            fi
             echo "Automated ${device_type} run complete."
         done
     done
 done
+
+if [ $setup_rc > 0 -o $test_run_rc > 0 ]; then
+    echo "One or more iterations failed"
+    exit 1
+fi
 
 echo "Automated efs run complete."
 
