TEI-3668 Refactor provisioner error and exit handling
Use more concise logic so that execution and error handling are
all in the same place and flow.

Harden up the exit traps to ensure unprovision happens.  If the
exit trap does not complete this can be a source of node pool
leaks.

Signed-off-by: Brian J. Murrell <brian.murrell@intel.com>
Change-Id: I9283288ffb12c39f33601067a08b00c1128f9d5d
Reviewed-on: http://review.whamcloud.com/15533
Tested-by: Jenkins
Reviewed-by: Chris Gearing <chris.gearing@intel.com>
Tested-by: Chroma Test User <hpdd-devops@intel.com>
Reviewed-by: Joe Grund <joe.grund@intel.com>

diff --git a/chroma-manager/tests/framework/integration/existing_filesystem_configuration/jenkins_steps/main b/chroma-manager/tests/framework/integration/existing_filesystem_configuration/jenkins_steps/main
--- a/chroma-manager/tests/framework/integration/existing_filesystem_configuration/jenkins_steps/main
+++ b/chroma-manager/tests/framework/integration/existing_filesystem_configuration/jenkins_steps/main
@@ -26,27 +26,26 @@ echo
 trap "set +e
 set -x
 # Gather logs from nodes
-python chroma/chroma-manager/tests/integration/utils/chroma_log_collector.py $WORKSPACE/test_logs existing_filesystem_configuration_cluster_cfg.json
-
+python chroma/chroma-manager/tests/integration/utils/chroma_log_collector.py $WORKSPACE/test_logs existing_filesystem_configuration_cluster_cfg.json || true
 sed -e 's/provision\": *true/provision\": false/g' < provisioner_output.json | $PROVISIONER" EXIT
 
 # Provision cluster to run tests on
 PROVISION_START_TIME=$SECONDS
-rc=0
-cat provisioner_input.json | $PROVISIONER > provisioner_output.json || rc=$?
+
+if ! cat provisioner_input.json | $PROVISIONER > provisioner_output.json ||
+   [ ! -s provisioner_output.json ] ||
+   grep '"success": false' provisioner_output.json; then
+    echo "Cluster provisioner failed"
+    cat provisioner_output.json
+    exit 1
+else
+    cat provisioner_output.json
+    echo
+fi
 PROVISION_END_TIME=$SECONDS
 PROVISION_DURATION=$((PROVISION_END_TIME-PROVISION_START_TIME))
 echo "$PROVISION_DURATION" > $WORKSPACE/provision_duration.txt
 echo "Provision took $((PROVISION_DURATION/60)) minutes."
-
-cat provisioner_output.json
-echo
-
-if [ $rc != 0 ] || [ ! -s provisioner_output.json ] || grep '"success": false' provisioner_output.json; then
-    echo "Cluster provisioner failed"
-    cat provisioner_output.json
-    exit 1
-fi
 
 python chroma/chroma-manager/tests/framework/utils/provisioner_interface/provisioner_json2test_json.py provisioner_output.json existing_filesystem_configuration_cluster_cfg.json
 cat existing_filesystem_configuration_cluster_cfg.json
