HYD-5622 create_installer script does not clean up temp directory
The create_installer script has a directory naming mismatch between the
commands to make the temporary staging directory and the deletion of
that directory after the distribution tarball is created.

 - fix the directory name in the rm command so that it matches the
   name being created
 - remove the dir on exit, in case of an ERROR exit
 - use a better variable name for the backing store than the positional $1

Signed-off-by: Brian J. Murrell <brian.murrell@intel.com>
Change-Id: I7838793db1004a0e7aab546724c946260a2885bb
Reviewed-on: http://review.whamcloud.com/22513
Tested-by: Jenkins
Tested-by: Chroma Test User
Reviewed-by: Tom Nabarro <tom.nabarro@intel.com>
Reviewed-by: Joe Grund <joe.grund@intel.com>

diff --git a/chroma-bundles/create_installer.in b/chroma-bundles/create_installer.in
--- a/chroma-bundles/create_installer.in
+++ b/chroma-bundles/create_installer.in
@@ -71,7 +71,8 @@ EOF
 }
 
 case $1 in
-    zfs|ldiskfs) :
+    zfs|ldiskfs)
+        BACKING_STORE="$1"
     ;;
     *) usage
     ;;
@@ -81,9 +82,13 @@ for DISTRO in el6 el7; do
     if [ ! -d $DISTRO ]; then
         continue
     fi
-    rm -rf lustre-$1
-    mkdir -p lustre-$1
-    cd lustre-$1
+    rm -rf lustre-$BACKING_STORE
+    mkdir -p lustre-$BACKING_STORE
+
+    # arrange for cleanup of the dir on exit for any reason
+    trap "rm -rf lustre-$BACKING_STORE" EXIT
+    
+    cd lustre-$BACKING_STORE
 
     tar -xzf ../$DISTRO/lustre-[0-9]*-bundle.tar.gz
     ${1}_installer "$DISTRO"
@@ -91,7 +96,5 @@ for DISTRO in el6 el7; do
     chmod 755 install
     cd ..
 
-    tar czf lustre-$1-$DISTRO-installer.tar.gz lustre-$1
-
-    rm -rf lustre-$1-$DISTRO
+    tar czf lustre-$BACKING_STORE-$DISTRO-installer.tar.gz lustre-$BACKING_STORE
 done
