changes as per review comments from @brianjmurrell

diff --git a/chroma-manager/tests/framework/integration/shared_storage_configuration/full_cluster/cluster_setup b/chroma-manager/tests/framework/integration/shared_storage_configuration/full_cluster/cluster_setup
--- a/chroma-manager/tests/framework/integration/shared_storage_configuration/full_cluster/cluster_setup
+++ b/chroma-manager/tests/framework/integration/shared_storage_configuration/full_cluster/cluster_setup
@@ -123,12 +123,8 @@ source $CHROMA_DIR/chroma-manager/tests/framework/integration/utils/install_clie
 
 # Install and setup integration tests on integration test runner
 if ! $JENKINS; then
-    package_name="chroma-manager-integration-tests-*.x86_64.rpm"
-    locations="chroma-manager/dist\nchroma-manager/"
-    for location in $locations; do
-        [[ -z "$CMIT" ]] && CMIT=$(ls $location/$package_name)
-    done
-    [[ -z "$CMIT" ]] && echo "Could not find $package_name in locations: $locations"
+    CMIT=$(ls chroma-manager/dist/chroma-manager-integration-tests-*.x86_64.rpm)
+    [[ -z "$CMIT" ]] && (echo "Could not find chroma-manager/dist/chroma-manager-integration-tests package"; exit 1)
 fi
 scp $CMIT $CLUSTER_CONFIG root@$TEST_RUNNER:/root/
 ssh root@$TEST_RUNNER <<EOF
