HYD-6238 Get better diags when a job is aborted
Job aborts from Jenkins are causing nodes to not be returned to
the pool but there isn't enough information in the job abort debug
that I get to tell me why or even where to look.

Add more information to the job abort data.

- update the cleanup() to provide more diagnostic data

Signed-off-by: Brian J. Murrell <brian.murrell@intel.com>
Change-Id: Ic86f91157ac7c6871806ccce4cdda44858dd845e
Reviewed-on: http://review.whamcloud.com/21552
Tested-by: Jenkins
Tested-by: Chroma Test User
Reviewed-by: Kelsey Prantis <kelsey.prantis@intel.com>
Reviewed-by: Chris Gearing <chris.gearing@intel.com>

diff --git a/chroma-manager/tests/framework/integration/shared_storage_configuration/full_cluster/jenkins_steps/main b/chroma-manager/tests/framework/integration/shared_storage_configuration/full_cluster/jenkins_steps/main
--- a/chroma-manager/tests/framework/integration/shared_storage_configuration/full_cluster/jenkins_steps/main
+++ b/chroma-manager/tests/framework/integration/shared_storage_configuration/full_cluster/jenkins_steps/main
@@ -20,6 +20,7 @@ cleanup() {
     if $got_aborted; then
         tmpfile=/tmp/abort.$$.debug
         exec 2>$tmpfile
+        env >&2
     fi
     python chroma/chroma-manager/tests/integration/utils/chroma_log_collector.py $WORKSPACE/test_logs $CLUSTER_CONFIG | tee $WORKSPACE/log_collector_out 2>&1 || true
     # look for known failures in the logs
@@ -37,9 +38,22 @@ cleanup() {
         echo "bug: HYD-2948"
     fi
 
-    chroma/chroma-manager/tests/framework/utils/provisioner_interface/release_cluster || true
+    if [ -f chroma/chroma-manager/tests/framework/utils/provisioner_interface/release_cluster ]; then
+        chroma/chroma-manager/tests/framework/utils/provisioner_interface/release_cluster || true
+    else
+        {
+        echo "*****************************************************************"
+        echo "chroma/chroma-manager/tests/framework/utils/provisioner_interface/release_cluster could not be found"
+        if $got_aborted; then
+            echo "this job was aborted!!"
+        fi
+        pwd
+        ls -l chroma
+        echo "*****************************************************************"
+        } >&2
+    fi
 
-    echo "exit trap done"
+    echo "exit trap done" >&2
     if [ -n "$tmpfile" -a -e "$tmpfile" ]; then
         cat $tmpfile | mail -s "job aborted" brian.murrell@intel.com
         #rm $tmpfile
