HYD-3448 Store and retrieve PIP externals in a git repo
chroma-externals: 11473/6
Signed-off-by: Brian J. Murrell <brian.murrell@intel.com>
Change-Id: I5d2c5d360f4c626ce1c9d710d7a6f423154a88ed
Reviewed-on: http://review.whamcloud.com/11475
Reviewed-by: Kelsey Prantis <kelsey.prantis@intel.com>
Tested-by: Jenkins
Tested-by: Chroma Test User <hpdd-devops@intel.com>
Reviewed-by: Joe Grund <joe.grund@intel.com>
Tested-by: Joe Grund <joe.grund@intel.com>

diff --git a/chroma-manager/tests/framework/gui/cluster_setup b/chroma-manager/tests/framework/gui/cluster_setup
--- a/chroma-manager/tests/framework/gui/cluster_setup
+++ b/chroma-manager/tests/framework/gui/cluster_setup
@@ -93,7 +93,12 @@ for package in importlib greenlet gevent psycopg2 pygraphviz; do
 done
 
 # Install the remaining pip requirements
-python tests/utils/pip_install_requirements.py ~/pip_cache
+if ! python tests/utils/pip_install_requirements.py $(pwd)/../chroma-externals; then
+  rc=${PIPESTATUS[0]}
+  echo "failed to install Python requirements from $(pwd)/../chroma-externals:"
+  ls -l $(pwd)/../chroma-externals
+  exit $rc
+fi
 
 # Install npm-based requirements
 cd chroma_ui
